alioth: Pocketmode: Define used libraries * Trigger build error in A14 build system
error: mismatch in the <uses-library> tags between the build system and the manifest:
  - required libraries in build system: []
                   vs. in the manifest: []
  - optional libraries in build system: []
                   vs. in the manifest: [androidx.window.extensions, androidx.window.sidecar]